# -*- coding: utf-8 -*-
"""data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCOravFouLKzC7ZWW0DXDMaqg6dAZ9EQ

# Merging Two Raw University Datasets

This notebook takes two raw, independently-formatted datasets (`raw1.csv` and `raw2.csv`) —
each with its own column naming convention — and merges them into a single combined dataset.

**Note:** This step only renames columns to a common schema and merges. No cleaning
(deduplication, missing value handling, text normalization) is performed here — that is
handled separately.

**Workflow:**
1. Load `raw1.csv` and `raw2.csv`
2. Inspect column names
3. Rename columns to a common schema
4. Merge on university ID + year
5. Save the merged dataset
"""

import pandas as pd

pd.set_option('display.max_columns', None)

"""## 1. Load the raw datasets"""

raw1 = pd.read_csv('raw1.csv')
raw2 = pd.read_csv('raw2.csv')

print("raw1 shape:", raw1.shape)
print("raw2 shape:", raw2.shape)

print("raw1 columns:")
print(raw1.columns.tolist())
print()
print("raw2 columns:")
print(raw2.columns.tolist())

raw1.head()

raw2.head()

"""## 2. Standardize column names

Each dataset's column names are mapped to a single common schema so the two can be joined
correctly (no other changes are made to the underlying data).
"""

rename1 = {
    'Univ_ID': 'university_id',
    'Year': 'year',
    'University_Name': 'university_name',
    'World Rank': 'world_rank',
    'Natl_Rank': 'national_rank',
    'Overall_Score': 'overall_score',
    'Country': 'country',
    'Region': 'region',
    'City': 'city',
    'Univ_Type': 'university_type',
    'Academic_Rep_Score': 'academic_reputation_score',
    'Employer_Rep_Score': 'employer_reputation_score',
    'Citations_Score': 'citations_score',
    'Publications': 'publications_count',
    'Citations': 'citations_count',
    'Citations_Per_Faculty': 'citations_per_faculty',
    'H_Index': 'h_index',
    'Research_Output_Score': 'research_output_score',
    'Research_Productivity_Index': 'research_productivity_index',
    'Subject_Field': 'subject_field',
}

rename2 = {
    'uni_id': 'university_id',
    'yr': 'year',
    'Total_Students': 'total_students',
    'Intl_Students_Count': 'international_students_count',
    'Intl_Student_Ratio_pct': 'international_student_ratio',
    'Faculty_Count': 'faculty_count',
    'Faculty_Student_Ratio': 'faculty_to_student_ratio',
    'Gender_Ratio': 'gender_ratio',
    'Female_Pct': 'female_percentage',
    'Male_Pct': 'male_percentage',
    'Degree_Level': 'degree_level',
    'UG_Count': 'undergraduate_count',
    'PG_Count': 'postgraduate_count',
    'Country_Avg_Rank': 'country_avg_rank',
    'Univ_Ranked_Count': 'universities_ranked_count',
    'Best_Univ_Rank': 'best_university_rank',
    'Country_Avg_Score': 'country_avg_overall_score',
    'Country_Avg_Acad_Rep': 'country_avg_academic_reputation',
    'Country_Avg_Citations': 'country_avg_citations',
    'Country_Avg_Intl_Ratio': 'country_avg_international_ratio',
}

raw1_renamed = raw1.rename(columns=rename1)
raw2_renamed = raw2.rename(columns=rename2)

print(raw1_renamed.columns.tolist())
print(raw2_renamed.columns.tolist())

"""## 3. Merge the two datasets

Both datasets share a common key: `university_id` + `year`. We merge on these columns.
"""

merged_df = pd.merge(
    raw1_renamed,
    raw2_renamed,
    on=['university_id', 'year'],
    how='inner'
)

print("Merged shape:", merged_df.shape)
merged_df.head()

print("Merged columns:")
print(merged_df.columns.tolist())

"""## 4. Save the merged dataset"""

merged_df.to_csv('university_raw_data.csv', index=False)
print("Saved university_raw_data.csv with shape:", merged_df.shape)