{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9877455b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pandas version: 3.0.2\n",
      "NumPy version: 2.4.4\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "print(\"Pandas version:\", pd.__version__)\n",
    "print(\"NumPy version:\", np.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "89a61ea4",
   "metadata": {},
   "outputs": [],
   "source": [
    "qs = pd.read_csv(\"Data2/QS2024.csv\",encoding=\"latin1\")\n",
    "the = pd.read_csv(\"Data2/QS2025.csv\",encoding=\"latin1\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2ff60904",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>RANK_2025</th>\n",
       "      <th>RANK_2024</th>\n",
       "      <th>Institution_Name</th>\n",
       "      <th>Location</th>\n",
       "      <th>Region</th>\n",
       "      <th>SIZE</th>\n",
       "      <th>FOCUS</th>\n",
       "      <th>RES.</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>Academic_Reputation_Score</th>\n",
       "      <th>...</th>\n",
       "      <th>International_Faculty_Rank</th>\n",
       "      <th>International_Students_Score</th>\n",
       "      <th>International_Students_Rank</th>\n",
       "      <th>International_Research_Network_Score</th>\n",
       "      <th>International_Research_Network_Rank</th>\n",
       "      <th>Employment_Outcomes_Score</th>\n",
       "      <th>Employment_Outcomes_Rank</th>\n",
       "      <th>Sustainability_Score</th>\n",
       "      <th>Sustainability_Rank</th>\n",
       "      <th>Overall_Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>United States</td>\n",
       "      <td>Americas</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>B</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>100</td>\n",
       "      <td>86.8</td>\n",
       "      <td>143</td>\n",
       "      <td>96.0</td>\n",
       "      <td>58</td>\n",
       "      <td>100.0</td>\n",
       "      <td>8</td>\n",
       "      <td>99.0</td>\n",
       "      <td>15=</td>\n",
       "      <td>100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>Imperial College London</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>98.5</td>\n",
       "      <td>...</td>\n",
       "      <td>66</td>\n",
       "      <td>99.6</td>\n",
       "      <td>44</td>\n",
       "      <td>97.4</td>\n",
       "      <td>34</td>\n",
       "      <td>93.4</td>\n",
       "      <td>61</td>\n",
       "      <td>99.7</td>\n",
       "      <td>6</td>\n",
       "      <td>98.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>120</td>\n",
       "      <td>97.7</td>\n",
       "      <td>73</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>100.0</td>\n",
       "      <td>3</td>\n",
       "      <td>85.0</td>\n",
       "      <td>126</td>\n",
       "      <td>96.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>B</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>269</td>\n",
       "      <td>69.0</td>\n",
       "      <td>215</td>\n",
       "      <td>99.6</td>\n",
       "      <td>5</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>84.4</td>\n",
       "      <td>130</td>\n",
       "      <td>96.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>2</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>73</td>\n",
       "      <td>94.8</td>\n",
       "      <td>98</td>\n",
       "      <td>99.3</td>\n",
       "      <td>10</td>\n",
       "      <td>100.0</td>\n",
       "      <td>5</td>\n",
       "      <td>84.8</td>\n",
       "      <td>127=</td>\n",
       "      <td>96.7</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 28 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  RANK_2025 RANK_2024                              Institution_Name  \\\n",
       "0         1         1  Massachusetts Institute of Technology (MIT)    \n",
       "1         2         6                       Imperial College London   \n",
       "2         3         3                          University of Oxford   \n",
       "3         4         4                            Harvard University   \n",
       "4         5         2                       University of Cambridge   \n",
       "\n",
       "         Location    Region SIZE FOCUS RES. STATUS  Academic_Reputation_Score  \\\n",
       "0   United States  Americas    M    CO   VH      B                      100.0   \n",
       "1  United Kingdom    Europe    L    FC   VH      A                       98.5   \n",
       "2  United Kingdom    Europe    L    FC   VH      A                      100.0   \n",
       "3   United States  Americas    L    FC   VH      B                      100.0   \n",
       "4  United Kingdom    Europe    L    FC   VH      A                      100.0   \n",
       "\n",
       "   ... International_Faculty_Rank  International_Students_Score  \\\n",
       "0  ...                        100                          86.8   \n",
       "1  ...                         66                          99.6   \n",
       "2  ...                        120                          97.7   \n",
       "3  ...                        269                          69.0   \n",
       "4  ...                         73                          94.8   \n",
       "\n",
       "  International_Students_Rank  International_Research_Network_Score  \\\n",
       "0                         143                                  96.0   \n",
       "1                          44                                  97.4   \n",
       "2                          73                                 100.0   \n",
       "3                         215                                  99.6   \n",
       "4                          98                                  99.3   \n",
       "\n",
       "  International_Research_Network_Rank  Employment_Outcomes_Score  \\\n",
       "0                                  58                      100.0   \n",
       "1                                  34                       93.4   \n",
       "2                                   1                      100.0   \n",
       "3                                   5                      100.0   \n",
       "4                                  10                      100.0   \n",
       "\n",
       "  Employment_Outcomes_Rank  Sustainability_Score Sustainability_Rank  \\\n",
       "0                        8                  99.0                 15=   \n",
       "1                       61                  99.7                   6   \n",
       "2                        3                  85.0                 126   \n",
       "3                        1                  84.4                 130   \n",
       "4                        5                  84.8                127=   \n",
       "\n",
       "   Overall_Score  \n",
       "0            100  \n",
       "1           98.5  \n",
       "2           96.9  \n",
       "3           96.8  \n",
       "4           96.7  \n",
       "\n",
       "[5 rows x 28 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qs.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b9852e13",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ï»¿2024 RANK</th>\n",
       "      <th>2023 RANK</th>\n",
       "      <th>Institution Name</th>\n",
       "      <th>Country Code</th>\n",
       "      <th>Country</th>\n",
       "      <th>SIZE</th>\n",
       "      <th>FOCUS</th>\n",
       "      <th>RES.</th>\n",
       "      <th>AGE</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>...</th>\n",
       "      <th>International Faculty Rank</th>\n",
       "      <th>International Students Score</th>\n",
       "      <th>International Students Rank</th>\n",
       "      <th>International Research Network Score</th>\n",
       "      <th>International Research Network Rank</th>\n",
       "      <th>Employment Outcomes Score</th>\n",
       "      <th>Employment Outcomes Rank</th>\n",
       "      <th>Sustainability Score</th>\n",
       "      <th>Sustainability Rank</th>\n",
       "      <th>Overall SCORE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>rank display</td>\n",
       "      <td>rank display2</td>\n",
       "      <td>institution</td>\n",
       "      <td>location code</td>\n",
       "      <td>location</td>\n",
       "      <td>size</td>\n",
       "      <td>focus</td>\n",
       "      <td>research</td>\n",
       "      <td>age band</td>\n",
       "      <td>status</td>\n",
       "      <td>...</td>\n",
       "      <td>ifr rank</td>\n",
       "      <td>isr score</td>\n",
       "      <td>isr rank</td>\n",
       "      <td>irn score</td>\n",
       "      <td>irn rank</td>\n",
       "      <td>ger score</td>\n",
       "      <td>ger rank</td>\n",
       "      <td>SUS SCORE</td>\n",
       "      <td>SUS RANK</td>\n",
       "      <td>Overall Score</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>B</td>\n",
       "      <td>...</td>\n",
       "      <td>56</td>\n",
       "      <td>88.2</td>\n",
       "      <td>128</td>\n",
       "      <td>94.3</td>\n",
       "      <td>58</td>\n",
       "      <td>100</td>\n",
       "      <td>4</td>\n",
       "      <td>95.2</td>\n",
       "      <td>51</td>\n",
       "      <td>100.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>UK</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>A</td>\n",
       "      <td>...</td>\n",
       "      <td>64</td>\n",
       "      <td>95.8</td>\n",
       "      <td>85</td>\n",
       "      <td>99.9</td>\n",
       "      <td>7</td>\n",
       "      <td>100</td>\n",
       "      <td>6</td>\n",
       "      <td>97.3</td>\n",
       "      <td>33=</td>\n",
       "      <td>99.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>UK</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>A</td>\n",
       "      <td>...</td>\n",
       "      <td>110</td>\n",
       "      <td>98.2</td>\n",
       "      <td>60</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>100</td>\n",
       "      <td>3</td>\n",
       "      <td>97.8</td>\n",
       "      <td>26=</td>\n",
       "      <td>98.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>B</td>\n",
       "      <td>...</td>\n",
       "      <td>210</td>\n",
       "      <td>66.8</td>\n",
       "      <td>223</td>\n",
       "      <td>100.0</td>\n",
       "      <td>5</td>\n",
       "      <td>100</td>\n",
       "      <td>1</td>\n",
       "      <td>96.7</td>\n",
       "      <td>39</td>\n",
       "      <td>98.3</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 29 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   ï»¿2024 RANK      2023 RANK                              Institution Name  \\\n",
       "0  rank display  rank display2                                   institution   \n",
       "1             1              1  Massachusetts Institute of Technology (MIT)    \n",
       "2             2              2                       University of Cambridge   \n",
       "3             3              4                          University of Oxford   \n",
       "4             4              5                            Harvard University   \n",
       "\n",
       "    Country Code         Country  SIZE  FOCUS      RES.       AGE  STATUS  \\\n",
       "0  location code        location  size  focus  research  age band  status   \n",
       "1             US   United States     M     CO        VH         5       B   \n",
       "2             UK  United Kingdom     L     FC        VH         5       A   \n",
       "3             UK  United Kingdom     L     FC        VH         5       A   \n",
       "4             US   United States     L     FC        VH         5       B   \n",
       "\n",
       "   ... International Faculty Rank International Students Score  \\\n",
       "0  ...                   ifr rank                    isr score   \n",
       "1  ...                         56                         88.2   \n",
       "2  ...                         64                         95.8   \n",
       "3  ...                        110                         98.2   \n",
       "4  ...                        210                         66.8   \n",
       "\n",
       "  International Students Rank International Research Network Score  \\\n",
       "0                    isr rank                            irn score   \n",
       "1                         128                                 94.3   \n",
       "2                          85                                 99.9   \n",
       "3                          60                                100.0   \n",
       "4                         223                                100.0   \n",
       "\n",
       "  International Research Network Rank Employment Outcomes Score  \\\n",
       "0                            irn rank                 ger score   \n",
       "1                                  58                       100   \n",
       "2                                   7                       100   \n",
       "3                                   1                       100   \n",
       "4                                   5                       100   \n",
       "\n",
       "  Employment Outcomes Rank Sustainability Score Sustainability Rank  \\\n",
       "0                 ger rank            SUS SCORE            SUS RANK   \n",
       "1                        4                 95.2                  51   \n",
       "2                        6                 97.3                 33=   \n",
       "3                        3                 97.8                 26=   \n",
       "4                        1                 96.7                  39   \n",
       "\n",
       "   Overall SCORE  \n",
       "0  Overall Score  \n",
       "1          100.0  \n",
       "2           99.2  \n",
       "3           98.9  \n",
       "4           98.3  \n",
       "\n",
       "[5 rows x 29 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5ac16178",
   "metadata": {},
   "outputs": [],
   "source": [
    "the.rename(columns={\n",
    "    \"Institution Name\":\"Institution_Name\"\n",
    "}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "84e4910b",
   "metadata": {},
   "outputs": [],
   "source": [
    "times = pd.read_csv(\"Data2/timesData.csv\")\n",
    "\n",
    "shanghai = pd.read_csv(\"Data2/shanghaiData.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "11000227",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>world_rank</th>\n",
       "      <th>university_name</th>\n",
       "      <th>country</th>\n",
       "      <th>teaching</th>\n",
       "      <th>international</th>\n",
       "      <th>research</th>\n",
       "      <th>citations</th>\n",
       "      <th>income</th>\n",
       "      <th>total_score</th>\n",
       "      <th>num_students</th>\n",
       "      <th>student_staff_ratio</th>\n",
       "      <th>international_students</th>\n",
       "      <th>female_male_ratio</th>\n",
       "      <th>year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>99.7</td>\n",
       "      <td>72.4</td>\n",
       "      <td>98.7</td>\n",
       "      <td>98.8</td>\n",
       "      <td>34.5</td>\n",
       "      <td>96.1</td>\n",
       "      <td>20,152</td>\n",
       "      <td>8.9</td>\n",
       "      <td>25%</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>California Institute of Technology</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>97.7</td>\n",
       "      <td>54.6</td>\n",
       "      <td>98.0</td>\n",
       "      <td>99.9</td>\n",
       "      <td>83.7</td>\n",
       "      <td>96.0</td>\n",
       "      <td>2,243</td>\n",
       "      <td>6.9</td>\n",
       "      <td>27%</td>\n",
       "      <td>33 : 67</td>\n",
       "      <td>2011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Massachusetts Institute of Technology</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>97.8</td>\n",
       "      <td>82.3</td>\n",
       "      <td>91.4</td>\n",
       "      <td>99.9</td>\n",
       "      <td>87.5</td>\n",
       "      <td>95.6</td>\n",
       "      <td>11,074</td>\n",
       "      <td>9.0</td>\n",
       "      <td>33%</td>\n",
       "      <td>37 : 63</td>\n",
       "      <td>2011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>98.3</td>\n",
       "      <td>29.5</td>\n",
       "      <td>98.1</td>\n",
       "      <td>99.2</td>\n",
       "      <td>64.3</td>\n",
       "      <td>94.3</td>\n",
       "      <td>15,596</td>\n",
       "      <td>7.8</td>\n",
       "      <td>22%</td>\n",
       "      <td>42 : 58</td>\n",
       "      <td>2011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Princeton University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>90.9</td>\n",
       "      <td>70.3</td>\n",
       "      <td>95.4</td>\n",
       "      <td>99.9</td>\n",
       "      <td>-</td>\n",
       "      <td>94.2</td>\n",
       "      <td>7,929</td>\n",
       "      <td>8.4</td>\n",
       "      <td>27%</td>\n",
       "      <td>45 : 55</td>\n",
       "      <td>2011</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  world_rank                        university_name                   country  \\\n",
       "0          1                     Harvard University  United States of America   \n",
       "1          2     California Institute of Technology  United States of America   \n",
       "2          3  Massachusetts Institute of Technology  United States of America   \n",
       "3          4                    Stanford University  United States of America   \n",
       "4          5                   Princeton University  United States of America   \n",
       "\n",
       "   teaching international  research  citations income total_score  \\\n",
       "0      99.7          72.4      98.7       98.8   34.5        96.1   \n",
       "1      97.7          54.6      98.0       99.9   83.7        96.0   \n",
       "2      97.8          82.3      91.4       99.9   87.5        95.6   \n",
       "3      98.3          29.5      98.1       99.2   64.3        94.3   \n",
       "4      90.9          70.3      95.4       99.9      -        94.2   \n",
       "\n",
       "  num_students  student_staff_ratio international_students female_male_ratio  \\\n",
       "0       20,152                  8.9                    25%               NaN   \n",
       "1        2,243                  6.9                    27%           33 : 67   \n",
       "2       11,074                  9.0                    33%           37 : 63   \n",
       "3       15,596                  7.8                    22%           42 : 58   \n",
       "4        7,929                  8.4                    27%           45 : 55   \n",
       "\n",
       "   year  \n",
       "0  2011  \n",
       "1  2011  \n",
       "2  2011  \n",
       "3  2011  \n",
       "4  2011  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "times.head()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "4153203a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>world_rank</th>\n",
       "      <th>university_name</th>\n",
       "      <th>national_rank</th>\n",
       "      <th>total_score</th>\n",
       "      <th>alumni</th>\n",
       "      <th>award</th>\n",
       "      <th>hici</th>\n",
       "      <th>ns</th>\n",
       "      <th>pub</th>\n",
       "      <th>pcp</th>\n",
       "      <th>year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>1</td>\n",
       "      <td>100.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>72.4</td>\n",
       "      <td>2005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>1</td>\n",
       "      <td>73.6</td>\n",
       "      <td>99.8</td>\n",
       "      <td>93.4</td>\n",
       "      <td>53.3</td>\n",
       "      <td>56.6</td>\n",
       "      <td>70.9</td>\n",
       "      <td>66.9</td>\n",
       "      <td>2005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>2</td>\n",
       "      <td>73.4</td>\n",
       "      <td>41.1</td>\n",
       "      <td>72.2</td>\n",
       "      <td>88.5</td>\n",
       "      <td>70.9</td>\n",
       "      <td>72.3</td>\n",
       "      <td>65.0</td>\n",
       "      <td>2005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>University of California, Berkeley</td>\n",
       "      <td>3</td>\n",
       "      <td>72.8</td>\n",
       "      <td>71.8</td>\n",
       "      <td>76.0</td>\n",
       "      <td>69.4</td>\n",
       "      <td>73.9</td>\n",
       "      <td>72.2</td>\n",
       "      <td>52.7</td>\n",
       "      <td>2005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>4</td>\n",
       "      <td>70.1</td>\n",
       "      <td>74.0</td>\n",
       "      <td>80.6</td>\n",
       "      <td>66.7</td>\n",
       "      <td>65.8</td>\n",
       "      <td>64.3</td>\n",
       "      <td>53.0</td>\n",
       "      <td>2005</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  world_rank                              university_name national_rank  \\\n",
       "0          1                           Harvard University             1   \n",
       "1          2                      University of Cambridge             1   \n",
       "2          3                          Stanford University             2   \n",
       "3          4           University of California, Berkeley             3   \n",
       "4          5  Massachusetts Institute of Technology (MIT)             4   \n",
       "\n",
       "   total_score  alumni  award   hici     ns    pub   pcp  year  \n",
       "0        100.0   100.0  100.0  100.0  100.0  100.0  72.4  2005  \n",
       "1         73.6    99.8   93.4   53.3   56.6   70.9  66.9  2005  \n",
       "2         73.4    41.1   72.2   88.5   70.9   72.3  65.0  2005  \n",
       "3         72.8    71.8   76.0   69.4   73.9   72.2  52.7  2005  \n",
       "4         70.1    74.0   80.6   66.7   65.8   64.3  53.0  2005  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "shanghai.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7bf0a3fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "qs.rename(columns={\n",
    "    \"Institution_Name\": \"university_name\"\n",
    "}, inplace=True)\n",
    "\n",
    "the.rename(columns={\n",
    "    \"Institution Name\": \"university_name\"\n",
    "}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "dd4a4568",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ï»¿2024 RANK</th>\n",
       "      <th>2023 RANK</th>\n",
       "      <th>university_name</th>\n",
       "      <th>Country Code</th>\n",
       "      <th>Country</th>\n",
       "      <th>SIZE</th>\n",
       "      <th>FOCUS</th>\n",
       "      <th>RES.</th>\n",
       "      <th>AGE</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>...</th>\n",
       "      <th>International Faculty Rank</th>\n",
       "      <th>International Students Score</th>\n",
       "      <th>International Students Rank</th>\n",
       "      <th>International Research Network Score</th>\n",
       "      <th>International Research Network Rank</th>\n",
       "      <th>Employment Outcomes Score</th>\n",
       "      <th>Employment Outcomes Rank</th>\n",
       "      <th>Sustainability Score</th>\n",
       "      <th>Sustainability Rank</th>\n",
       "      <th>Overall SCORE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>rank display</td>\n",
       "      <td>rank display2</td>\n",
       "      <td>institution</td>\n",
       "      <td>location code</td>\n",
       "      <td>location</td>\n",
       "      <td>size</td>\n",
       "      <td>focus</td>\n",
       "      <td>research</td>\n",
       "      <td>age band</td>\n",
       "      <td>status</td>\n",
       "      <td>...</td>\n",
       "      <td>ifr rank</td>\n",
       "      <td>isr score</td>\n",
       "      <td>isr rank</td>\n",
       "      <td>irn score</td>\n",
       "      <td>irn rank</td>\n",
       "      <td>ger score</td>\n",
       "      <td>ger rank</td>\n",
       "      <td>SUS SCORE</td>\n",
       "      <td>SUS RANK</td>\n",
       "      <td>Overall Score</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>B</td>\n",
       "      <td>...</td>\n",
       "      <td>56</td>\n",
       "      <td>88.2</td>\n",
       "      <td>128</td>\n",
       "      <td>94.3</td>\n",
       "      <td>58</td>\n",
       "      <td>100</td>\n",
       "      <td>4</td>\n",
       "      <td>95.2</td>\n",
       "      <td>51</td>\n",
       "      <td>100.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>UK</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>A</td>\n",
       "      <td>...</td>\n",
       "      <td>64</td>\n",
       "      <td>95.8</td>\n",
       "      <td>85</td>\n",
       "      <td>99.9</td>\n",
       "      <td>7</td>\n",
       "      <td>100</td>\n",
       "      <td>6</td>\n",
       "      <td>97.3</td>\n",
       "      <td>33=</td>\n",
       "      <td>99.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>UK</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>A</td>\n",
       "      <td>...</td>\n",
       "      <td>110</td>\n",
       "      <td>98.2</td>\n",
       "      <td>60</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>100</td>\n",
       "      <td>3</td>\n",
       "      <td>97.8</td>\n",
       "      <td>26=</td>\n",
       "      <td>98.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>5</td>\n",
       "      <td>B</td>\n",
       "      <td>...</td>\n",
       "      <td>210</td>\n",
       "      <td>66.8</td>\n",
       "      <td>223</td>\n",
       "      <td>100.0</td>\n",
       "      <td>5</td>\n",
       "      <td>100</td>\n",
       "      <td>1</td>\n",
       "      <td>96.7</td>\n",
       "      <td>39</td>\n",
       "      <td>98.3</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 29 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   ï»¿2024 RANK      2023 RANK                               university_name  \\\n",
       "0  rank display  rank display2                                   institution   \n",
       "1             1              1  Massachusetts Institute of Technology (MIT)    \n",
       "2             2              2                       University of Cambridge   \n",
       "3             3              4                          University of Oxford   \n",
       "4             4              5                            Harvard University   \n",
       "\n",
       "    Country Code         Country  SIZE  FOCUS      RES.       AGE  STATUS  \\\n",
       "0  location code        location  size  focus  research  age band  status   \n",
       "1             US   United States     M     CO        VH         5       B   \n",
       "2             UK  United Kingdom     L     FC        VH         5       A   \n",
       "3             UK  United Kingdom     L     FC        VH         5       A   \n",
       "4             US   United States     L     FC        VH         5       B   \n",
       "\n",
       "   ... International Faculty Rank International Students Score  \\\n",
       "0  ...                   ifr rank                    isr score   \n",
       "1  ...                         56                         88.2   \n",
       "2  ...                         64                         95.8   \n",
       "3  ...                        110                         98.2   \n",
       "4  ...                        210                         66.8   \n",
       "\n",
       "  International Students Rank International Research Network Score  \\\n",
       "0                    isr rank                            irn score   \n",
       "1                         128                                 94.3   \n",
       "2                          85                                 99.9   \n",
       "3                          60                                100.0   \n",
       "4                         223                                100.0   \n",
       "\n",
       "  International Research Network Rank Employment Outcomes Score  \\\n",
       "0                            irn rank                 ger score   \n",
       "1                                  58                       100   \n",
       "2                                   7                       100   \n",
       "3                                   1                       100   \n",
       "4                                   5                       100   \n",
       "\n",
       "  Employment Outcomes Rank Sustainability Score Sustainability Rank  \\\n",
       "0                 ger rank            SUS SCORE            SUS RANK   \n",
       "1                        4                 95.2                  51   \n",
       "2                        6                 97.3                 33=   \n",
       "3                        3                 97.8                 26=   \n",
       "4                        1                 96.7                  39   \n",
       "\n",
       "   Overall SCORE  \n",
       "0  Overall Score  \n",
       "1          100.0  \n",
       "2           99.2  \n",
       "3           98.9  \n",
       "4           98.3  \n",
       "\n",
       "[5 rows x 29 columns]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "405509e7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>RANK_2025</th>\n",
       "      <th>RANK_2024</th>\n",
       "      <th>university_name</th>\n",
       "      <th>Location</th>\n",
       "      <th>Region</th>\n",
       "      <th>SIZE</th>\n",
       "      <th>FOCUS</th>\n",
       "      <th>RES.</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>Academic_Reputation_Score</th>\n",
       "      <th>...</th>\n",
       "      <th>International_Faculty_Rank</th>\n",
       "      <th>International_Students_Score</th>\n",
       "      <th>International_Students_Rank</th>\n",
       "      <th>International_Research_Network_Score</th>\n",
       "      <th>International_Research_Network_Rank</th>\n",
       "      <th>Employment_Outcomes_Score</th>\n",
       "      <th>Employment_Outcomes_Rank</th>\n",
       "      <th>Sustainability_Score</th>\n",
       "      <th>Sustainability_Rank</th>\n",
       "      <th>Overall_Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>United States</td>\n",
       "      <td>Americas</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>B</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>100</td>\n",
       "      <td>86.8</td>\n",
       "      <td>143</td>\n",
       "      <td>96.0</td>\n",
       "      <td>58</td>\n",
       "      <td>100.0</td>\n",
       "      <td>8</td>\n",
       "      <td>99.0</td>\n",
       "      <td>15=</td>\n",
       "      <td>100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>Imperial College London</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>98.5</td>\n",
       "      <td>...</td>\n",
       "      <td>66</td>\n",
       "      <td>99.6</td>\n",
       "      <td>44</td>\n",
       "      <td>97.4</td>\n",
       "      <td>34</td>\n",
       "      <td>93.4</td>\n",
       "      <td>61</td>\n",
       "      <td>99.7</td>\n",
       "      <td>6</td>\n",
       "      <td>98.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>120</td>\n",
       "      <td>97.7</td>\n",
       "      <td>73</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>100.0</td>\n",
       "      <td>3</td>\n",
       "      <td>85.0</td>\n",
       "      <td>126</td>\n",
       "      <td>96.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>B</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>269</td>\n",
       "      <td>69.0</td>\n",
       "      <td>215</td>\n",
       "      <td>99.6</td>\n",
       "      <td>5</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>84.4</td>\n",
       "      <td>130</td>\n",
       "      <td>96.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>2</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>73</td>\n",
       "      <td>94.8</td>\n",
       "      <td>98</td>\n",
       "      <td>99.3</td>\n",
       "      <td>10</td>\n",
       "      <td>100.0</td>\n",
       "      <td>5</td>\n",
       "      <td>84.8</td>\n",
       "      <td>127=</td>\n",
       "      <td>96.7</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 28 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  RANK_2025 RANK_2024                               university_name  \\\n",
       "0         1         1  Massachusetts Institute of Technology (MIT)    \n",
       "1         2         6                       Imperial College London   \n",
       "2         3         3                          University of Oxford   \n",
       "3         4         4                            Harvard University   \n",
       "4         5         2                       University of Cambridge   \n",
       "\n",
       "         Location    Region SIZE FOCUS RES. STATUS  Academic_Reputation_Score  \\\n",
       "0   United States  Americas    M    CO   VH      B                      100.0   \n",
       "1  United Kingdom    Europe    L    FC   VH      A                       98.5   \n",
       "2  United Kingdom    Europe    L    FC   VH      A                      100.0   \n",
       "3   United States  Americas    L    FC   VH      B                      100.0   \n",
       "4  United Kingdom    Europe    L    FC   VH      A                      100.0   \n",
       "\n",
       "   ... International_Faculty_Rank  International_Students_Score  \\\n",
       "0  ...                        100                          86.8   \n",
       "1  ...                         66                          99.6   \n",
       "2  ...                        120                          97.7   \n",
       "3  ...                        269                          69.0   \n",
       "4  ...                         73                          94.8   \n",
       "\n",
       "  International_Students_Rank  International_Research_Network_Score  \\\n",
       "0                         143                                  96.0   \n",
       "1                          44                                  97.4   \n",
       "2                          73                                 100.0   \n",
       "3                         215                                  99.6   \n",
       "4                          98                                  99.3   \n",
       "\n",
       "  International_Research_Network_Rank  Employment_Outcomes_Score  \\\n",
       "0                                  58                      100.0   \n",
       "1                                  34                       93.4   \n",
       "2                                   1                      100.0   \n",
       "3                                   5                      100.0   \n",
       "4                                  10                      100.0   \n",
       "\n",
       "  Employment_Outcomes_Rank  Sustainability_Score Sustainability_Rank  \\\n",
       "0                        8                  99.0                 15=   \n",
       "1                       61                  99.7                   6   \n",
       "2                        3                  85.0                 126   \n",
       "3                        1                  84.4                 130   \n",
       "4                        5                  84.8                127=   \n",
       "\n",
       "   Overall_Score  \n",
       "0            100  \n",
       "1           98.5  \n",
       "2           96.9  \n",
       "3           96.8  \n",
       "4           96.7  \n",
       "\n",
       "[5 rows x 28 columns]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qs.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "9ee3e20b",
   "metadata": {},
   "outputs": [],
   "source": [
    "for df in [qs, the, times, shanghai]:\n",
    "    df[\"university_name\"] = (\n",
    "        df[\"university_name\"]\n",
    "        .str.strip()\n",
    "        .str.lower()\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "f9cd987d",
   "metadata": {},
   "outputs": [],
   "source": [
    "merged = pd.merge(\n",
    "    qs,\n",
    "    the,\n",
    "    on=\"university_name\",\n",
    "    how=\"outer\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "709301f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "merged = pd.merge(\n",
    "    merged,\n",
    "    times,\n",
    "    on=\"university_name\",\n",
    "    how=\"outer\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "c6cb214e",
   "metadata": {},
   "outputs": [],
   "source": [
    "merged = pd.merge(\n",
    "    merged,\n",
    "    shanghai,\n",
    "    on=\"university_name\",\n",
    "    how=\"outer\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "4947b314",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>RANK_2025</th>\n",
       "      <th>RANK_2024</th>\n",
       "      <th>university_name</th>\n",
       "      <th>Location</th>\n",
       "      <th>Region</th>\n",
       "      <th>SIZE_x</th>\n",
       "      <th>FOCUS_x</th>\n",
       "      <th>RES._x</th>\n",
       "      <th>STATUS_x</th>\n",
       "      <th>Academic_Reputation_Score</th>\n",
       "      <th>...</th>\n",
       "      <th>world_rank_y</th>\n",
       "      <th>national_rank</th>\n",
       "      <th>total_score_y</th>\n",
       "      <th>alumni</th>\n",
       "      <th>award</th>\n",
       "      <th>hici</th>\n",
       "      <th>ns</th>\n",
       "      <th>pub</th>\n",
       "      <th>pcp</th>\n",
       "      <th>year_y</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>306</td>\n",
       "      <td>336</td>\n",
       "      <td>aalborg university</td>\n",
       "      <td>Denmark</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>19.9</td>\n",
       "      <td>...</td>\n",
       "      <td>401-500</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>12.2</td>\n",
       "      <td>3.4</td>\n",
       "      <td>27.6</td>\n",
       "      <td>15.2</td>\n",
       "      <td>2014.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>306</td>\n",
       "      <td>336</td>\n",
       "      <td>aalborg university</td>\n",
       "      <td>Denmark</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>19.9</td>\n",
       "      <td>...</td>\n",
       "      <td>301-400</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>11.2</td>\n",
       "      <td>4.6</td>\n",
       "      <td>30.4</td>\n",
       "      <td>16.8</td>\n",
       "      <td>2015.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>306</td>\n",
       "      <td>336</td>\n",
       "      <td>aalborg university</td>\n",
       "      <td>Denmark</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>19.9</td>\n",
       "      <td>...</td>\n",
       "      <td>401-500</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>12.2</td>\n",
       "      <td>3.4</td>\n",
       "      <td>27.6</td>\n",
       "      <td>15.2</td>\n",
       "      <td>2014.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>306</td>\n",
       "      <td>336</td>\n",
       "      <td>aalborg university</td>\n",
       "      <td>Denmark</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>19.9</td>\n",
       "      <td>...</td>\n",
       "      <td>301-400</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>11.2</td>\n",
       "      <td>4.6</td>\n",
       "      <td>30.4</td>\n",
       "      <td>16.8</td>\n",
       "      <td>2015.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>306</td>\n",
       "      <td>336</td>\n",
       "      <td>aalborg university</td>\n",
       "      <td>Denmark</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>A</td>\n",
       "      <td>19.9</td>\n",
       "      <td>...</td>\n",
       "      <td>401-500</td>\n",
       "      <td>5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>12.2</td>\n",
       "      <td>3.4</td>\n",
       "      <td>27.6</td>\n",
       "      <td>15.2</td>\n",
       "      <td>2014.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 79 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  RANK_2025 RANK_2024     university_name Location  Region SIZE_x FOCUS_x  \\\n",
       "0       306       336  aalborg university  Denmark  Europe      L      FC   \n",
       "1       306       336  aalborg university  Denmark  Europe      L      FC   \n",
       "2       306       336  aalborg university  Denmark  Europe      L      FC   \n",
       "3       306       336  aalborg university  Denmark  Europe      L      FC   \n",
       "4       306       336  aalborg university  Denmark  Europe      L      FC   \n",
       "\n",
       "  RES._x STATUS_x  Academic_Reputation_Score  ... world_rank_y  national_rank  \\\n",
       "0     VH        A                       19.9  ...      401-500              5   \n",
       "1     VH        A                       19.9  ...      301-400              5   \n",
       "2     VH        A                       19.9  ...      401-500              5   \n",
       "3     VH        A                       19.9  ...      301-400              5   \n",
       "4     VH        A                       19.9  ...      401-500              5   \n",
       "\n",
       "  total_score_y  alumni award  hici   ns   pub   pcp  year_y  \n",
       "0           NaN     0.0   0.0  12.2  3.4  27.6  15.2  2014.0  \n",
       "1           NaN     0.0   0.0  11.2  4.6  30.4  16.8  2015.0  \n",
       "2           NaN     0.0   0.0  12.2  3.4  27.6  15.2  2014.0  \n",
       "3           NaN     0.0   0.0  11.2  4.6  30.4  16.8  2015.0  \n",
       "4           NaN     0.0   0.0  12.2  3.4  27.6  15.2  2014.0  \n",
       "\n",
       "[5 rows x 79 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "d0442158",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rows: (17661, 79)\n"
     ]
    }
   ],
   "source": [
    "print(\"Rows:\", merged.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "b1b0faf9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Duplicate university names: 15364\n"
     ]
    }
   ],
   "source": [
    "print(\"Duplicate university names:\",\n",
    "      merged[\"university_name\"].duplicated().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "7d8d028f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['world_rank',\n",
       " 'university_name',\n",
       " 'country',\n",
       " 'teaching',\n",
       " 'international',\n",
       " 'research',\n",
       " 'citations',\n",
       " 'income',\n",
       " 'total_score',\n",
       " 'num_students',\n",
       " 'student_staff_ratio',\n",
       " 'international_students',\n",
       " 'female_male_ratio',\n",
       " 'year']"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "times.columns.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "821c7626",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['RANK_2025',\n",
       " 'RANK_2024',\n",
       " 'university_name',\n",
       " 'Location',\n",
       " 'Region',\n",
       " 'SIZE_x',\n",
       " 'FOCUS_x',\n",
       " 'RES._x',\n",
       " 'STATUS_x',\n",
       " 'Academic_Reputation_Score',\n",
       " 'Academic_Reputation_Rank',\n",
       " 'Employer_Reputation_Score',\n",
       " 'Employer_Reputation_Rank',\n",
       " 'Faculty_Student_Score',\n",
       " 'Faculty_Student_Rank',\n",
       " 'Citations_per_Faculty_Score',\n",
       " 'Citations_per_Faculty_Rank',\n",
       " 'International_Faculty_Score',\n",
       " 'International_Faculty_Rank',\n",
       " 'International_Students_Score',\n",
       " 'International_Students_Rank',\n",
       " 'International_Research_Network_Score',\n",
       " 'International_Research_Network_Rank',\n",
       " 'Employment_Outcomes_Score',\n",
       " 'Employment_Outcomes_Rank',\n",
       " 'Sustainability_Score',\n",
       " 'Sustainability_Rank',\n",
       " 'Overall_Score',\n",
       " 'ï»¿2024 RANK',\n",
       " '2023 RANK',\n",
       " 'Country Code',\n",
       " 'Country',\n",
       " 'SIZE_y',\n",
       " 'FOCUS_y',\n",
       " 'RES._y',\n",
       " 'AGE',\n",
       " 'STATUS_y',\n",
       " 'Academic Reputation Score',\n",
       " 'Academic Reputation Rank',\n",
       " 'Employer Reputation Score',\n",
       " 'Employer Reputation Rank',\n",
       " 'Faculty Student Score',\n",
       " 'Faculty Student Rank',\n",
       " 'Citations per Faculty Score',\n",
       " 'Citations per Faculty Rank',\n",
       " 'International Faculty Score',\n",
       " 'International Faculty Rank',\n",
       " 'International Students Score',\n",
       " 'International Students Rank',\n",
       " 'International Research Network Score',\n",
       " 'International Research Network Rank',\n",
       " 'Employment Outcomes Score',\n",
       " 'Employment Outcomes Rank',\n",
       " 'Sustainability Score',\n",
       " 'Sustainability Rank',\n",
       " 'Overall SCORE',\n",
       " 'world_rank_x',\n",
       " 'country',\n",
       " 'teaching',\n",
       " 'international',\n",
       " 'research',\n",
       " 'citations',\n",
       " 'income',\n",
       " 'total_score_x',\n",
       " 'num_students',\n",
       " 'student_staff_ratio',\n",
       " 'international_students',\n",
       " 'female_male_ratio',\n",
       " 'year_x',\n",
       " 'world_rank_y',\n",
       " 'national_rank',\n",
       " 'total_score_y',\n",
       " 'alumni',\n",
       " 'award',\n",
       " 'hici',\n",
       " 'ns',\n",
       " 'pub',\n",
       " 'pcp',\n",
       " 'year_y']"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged.columns.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "09517364",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(17661, 79)"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "c8b279ed",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2603, 14)"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "times.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "bad6390d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n",
      "True\n",
      "True\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "print(\"teaching\" in merged.columns)\n",
    "print(\"international\" in merged.columns)\n",
    "print(\"research\" in merged.columns)\n",
    "print(\"num_students\" in merged.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "ac4bd732",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "university_name                     ✅ Present\n",
      "world_rank                          ❌ Missing\n",
      "national_rank                       ✅ Present\n",
      "overall_score                       ❌ Missing\n",
      "academic_reputation_score           ❌ Missing\n",
      "employer_reputation_score           ❌ Missing\n",
      "citations_score                     ❌ Missing\n",
      "publications_count                  ❌ Missing\n",
      "research                            ✅ Present\n",
      "international                       ✅ Present\n",
      "num_students                        ✅ Present\n",
      "student_staff_ratio                 ✅ Present\n",
      "international_students              ✅ Present\n",
      "female_male_ratio                   ✅ Present\n"
     ]
    }
   ],
   "source": [
    "required = [\n",
    "    \"university_name\",\n",
    "    \"world_rank\",\n",
    "    \"national_rank\",\n",
    "    \"overall_score\",\n",
    "    \"academic_reputation_score\",\n",
    "    \"employer_reputation_score\",\n",
    "    \"citations_score\",\n",
    "    \"publications_count\",\n",
    "    \"research\",\n",
    "    \"international\",\n",
    "    \"num_students\",\n",
    "    \"student_staff_ratio\",\n",
    "    \"international_students\",\n",
    "    \"female_male_ratio\"\n",
    "]\n",
    "\n",
    "for col in required:\n",
    "    print(f\"{col:<35} {'✅ Present' if col in merged.columns else '❌ Missing'}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "53e9a2a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "merged.to_csv(\"Data2/Merged_Raw_Dataset.csv\", index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
